# Generated by Django 3.2.9 on 2021-11-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emails_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='verify_key',
        ),
        migrations.AddField(
            model_name='emails',
            name='verified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
