# Generated by Django 3.2.9 on 2021-11-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('first_option', models.CharField(max_length=256)),
                ('second_option', models.CharField(max_length=256)),
                ('vote', models.CharField(choices=[(None, None), (None, None)], default=None, max_length=256)),
            ],
        ),
    ]
