# Generated by Django 3.2.9 on 2021-12-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('first_option', models.CharField(max_length=256)),
                ('second_option', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choice', models.CharField(max_length=256)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='votes.votes')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='users.emails')),
            ],
        ),
        migrations.AddConstraint(
            model_name='voters',
            constraint=models.UniqueConstraint(fields=('voter', 'vote'), name='vote_voter_unique_constraint'),
        ),
    ]
