# Generated by Django 3.2.9 on 2021-11-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('votes', '0002_remove_votes_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choice', models.CharField(max_length=256)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='votes.votes')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='users.emails')),
            ],
        ),
    ]
