# Generated by Django 3.2.9 on 2021-11-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20211108_0840'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voters',
            constraint=models.UniqueConstraint(fields=('voter', 'vote'), name='vote_voter_unique_constraint'),
        ),
    ]
